services:

  web:
    restart: always
    build: .
    expose:
      - 8000
    volumes:
      - ./backend:/home/backend

    command: /bin/sh -c 'python3 manage.py makemigrations; python3 manage.py migrate; gunicorn --chdir ./backend/ backend.wsgi:application --bind 0.0.0.0:8000 --reload;'
  

  db:
    image: postgres:14.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=here_is_a_super_secret_password_made_by_h4mid
      - POSTGRES_DB=book_shop


volumes:
  postgres_data:
  
